#!/usr/bin/env bash
# compose.sh — deterministic part of generate-workbench.
# Lays the scaffold into a target repo and composes AGENTS.md = framework core +
# the user's persona overlay. The judgment (obtaining the repo, locating core,
# discarding .persona, pointing to first task) stays in SKILL.md.
set -euo pipefail

usage() {
  echo "usage: compose.sh --persona <dir> --core <AGENTS.core.md> --scaffold <dir> --out <repo>" >&2
  exit 2
}

PERSONA="" CORE="" SCAFFOLD="" OUT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --persona)  PERSONA="$2"; shift 2 ;;
    --core)     CORE="$2"; shift 2 ;;
    --scaffold) SCAFFOLD="$2"; shift 2 ;;
    --out)      OUT="$2"; shift 2 ;;
    -h|--help)  usage ;;
    *) echo "compose.sh: unknown arg '$1'" >&2; usage ;;
  esac
done
[ -n "$PERSONA" ] && [ -n "$CORE" ] && [ -n "$SCAFFOLD" ] && [ -n "$OUT" ] || usage
[ -f "$CORE" ]                  || { echo "core not found: $CORE" >&2; exit 1; }
[ -d "$SCAFFOLD" ]              || { echo "scaffold not found: $SCAFFOLD" >&2; exit 1; }
[ -f "$PERSONA/overlay.md" ]    || { echo "persona overlay not found: $PERSONA/overlay.md" >&2; exit 1; }

# Pre-check: the persona contract. Catch a half-filled .persona/ before we scaffold,
# so failures point at the interview output rather than a malformed workbench.
[ -s "$PERSONA/overlay.md" ]    || { echo "persona overlay is empty: $PERSONA/overlay.md" >&2; exit 1; }
grep -qi '^#\+ *Language' "$PERSONA/overlay.md" \
  || echo "warning: overlay has no Language section — output language may default to English" >&2

mkdir -p "$OUT"

# 1) Lay the scaffold (profile defaults + empty knowledge). Engine (utils/skills/bin)
#    is NOT copied — it comes from the installed plugin, so the repo stays minimal.
for item in templates .github docs; do
  [ -e "$SCAFFOLD/$item" ] && cp -R "$SCAFFOLD/$item" "$OUT/$item"
done

# 2) codebases.yaml: the user's targets if interview captured any, else empty template.
if [ -f "$PERSONA/codebases.yaml" ]; then
  cp "$PERSONA/codebases.yaml" "$OUT/codebases.yaml"
elif [ -f "$SCAFFOLD/codebases.yaml" ]; then
  cp "$SCAFFOLD/codebases.yaml" "$OUT/codebases.yaml"
fi

# 3) Overlay = the persona's filled overlay (the user edits this later).
cp "$PERSONA/overlay.md" "$OUT/AGENTS.overlay.md"

# 4) Compose AGENTS.md = core + overlay, inline. Inline (not @include) so it reads
#    correctly in any tool and survives the plugin path changing; recompose on upgrade.
{
  cat <<'HDR'
# Workbench (composed — do not edit directly)

> Generated by `workbench-kit:generate-workbench` from the framework core + your
> persona overlay. To change: edit `AGENTS.overlay.md` (your rules) and recompose;
> the framework core is re-read from the `workbench-kit` plugin's scaffold. Operational output
> language follows the Language section in your overlay.

<!-- ===== FRAMEWORK CORE (from workbench plugin — do not edit here) ===== -->

HDR
  cat "$CORE"
  printf '\n<!-- ===== YOUR PERSONA (edit AGENTS.overlay.md, then recompose) ===== -->\n\n'
  cat "$PERSONA/overlay.md"
} > "$OUT/AGENTS.md"

# 5) CLAUDE.md compatibility symlink.
ln -sfn AGENTS.md "$OUT/CLAUDE.md"

# 6) Post-check: verify the workbench is well-formed. The skill no longer eyeballs the
#    result — the script asserts its own post-conditions and fails loudly if any miss,
#    so a bad compose can't slip through to the user.
fail=0
check() { # <description> <test-result(0=ok)>
  if [ "$2" -eq 0 ]; then echo "  ok   $1"; else echo "  FAIL $1" >&2; fail=1; fi
}
echo "verifying $OUT:"
check "AGENTS.md exists"                  "$([ -f "$OUT/AGENTS.md" ]; echo $?)"
check "AGENTS.md has framework core"      "$(grep -q 'FRAMEWORK CORE' "$OUT/AGENTS.md" 2>/dev/null; echo $?)"
check "AGENTS.md has persona overlay"     "$(grep -q 'YOUR PERSONA' "$OUT/AGENTS.md" 2>/dev/null; echo $?)"
check "AGENTS.overlay.md exists"          "$([ -f "$OUT/AGENTS.overlay.md" ]; echo $?)"
check "CLAUDE.md → AGENTS.md"             "$([ "$(readlink "$OUT/CLAUDE.md" 2>/dev/null)" = AGENTS.md ]; echo $?)"
check "docs/ skeleton (index.md)"         "$([ -f "$OUT/docs/index.md" ]; echo $?)"
check "codebases.yaml present"            "$([ -f "$OUT/codebases.yaml" ]; echo $?)"
check "engine NOT copied (no utils/)"     "$([ ! -e "$OUT/utils" ]; echo $?)"
if [ "$fail" -ne 0 ]; then echo "compose verification FAILED" >&2; exit 1; fi

echo "composed workbench at: $OUT ($(wc -l < "$OUT/AGENTS.md" | tr -d ' ') lines AGENTS.md, engine via plugin)"
