#!/usr/bin/env bash
# compose.sh — deterministic part of generate-workbench.
# Lays the scaffold into a target repo and composes AGENTS.md = framework core +
# the user's persona overlay. The judgment (obtaining the repo, locating core,
# discarding .persona, pointing to first task) stays in SKILL.md.
set -euo pipefail

usage() {
  echo "usage: compose.sh --persona <dir> --core <AGENTS.core.md> --scaffold <dir> --out <repo>" >&2
  exit 2
}

PERSONA="" CORE="" SCAFFOLD="" OUT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --persona)  PERSONA="$2"; shift 2 ;;
    --core)     CORE="$2"; shift 2 ;;
    --scaffold) SCAFFOLD="$2"; shift 2 ;;
    --out)      OUT="$2"; shift 2 ;;
    -h|--help)  usage ;;
    *) echo "compose.sh: unknown arg '$1'" >&2; usage ;;
  esac
done
[ -n "$PERSONA" ] && [ -n "$CORE" ] && [ -n "$SCAFFOLD" ] && [ -n "$OUT" ] || usage
[ -f "$CORE" ]                  || { echo "core not found: $CORE" >&2; exit 1; }
[ -d "$SCAFFOLD" ]              || { echo "scaffold not found: $SCAFFOLD" >&2; exit 1; }
[ -f "$PERSONA/overlay.md" ]    || { echo "persona overlay not found: $PERSONA/overlay.md" >&2; exit 1; }

mkdir -p "$OUT"

# 1) Lay the scaffold (profile defaults + empty knowledge). Engine (utils/skills/bin)
#    is NOT copied — it comes from the installed plugin, so the repo stays minimal.
for item in templates .github docs; do
  [ -e "$SCAFFOLD/$item" ] && cp -R "$SCAFFOLD/$item" "$OUT/$item"
done

# 2) codebases.yaml: the user's targets if interview captured any, else empty template.
if [ -f "$PERSONA/codebases.yaml" ]; then
  cp "$PERSONA/codebases.yaml" "$OUT/codebases.yaml"
elif [ -f "$SCAFFOLD/codebases.yaml" ]; then
  cp "$SCAFFOLD/codebases.yaml" "$OUT/codebases.yaml"
fi

# 3) Overlay = the persona's filled overlay (the user edits this later).
cp "$PERSONA/overlay.md" "$OUT/AGENTS.overlay.md"

# 4) Compose AGENTS.md = core + overlay, inline. Inline (not @include) so it reads
#    correctly in any tool and survives the plugin path changing; recompose on upgrade.
{
  cat <<'HDR'
# Workbench (composed — do not edit directly)

> Generated by `workbench-kit:generate-workbench` from the framework core + your
> persona overlay. To change: edit `AGENTS.overlay.md` (your rules) and recompose;
> the framework core comes from the installed `workbench` plugin. Operational output
> language follows the Language section in your overlay.

<!-- ===== FRAMEWORK CORE (from workbench plugin — do not edit here) ===== -->

HDR
  cat "$CORE"
  printf '\n<!-- ===== YOUR PERSONA (edit AGENTS.overlay.md, then recompose) ===== -->\n\n'
  cat "$PERSONA/overlay.md"
} > "$OUT/AGENTS.md"

# 5) CLAUDE.md compatibility symlink.
ln -sfn AGENTS.md "$OUT/CLAUDE.md"

echo "composed workbench at: $OUT"
echo "  AGENTS.md            ($(wc -l < "$OUT/AGENTS.md") lines, core+overlay)"
echo "  AGENTS.overlay.md    (your editable rules)"
[ -e "$OUT/docs" ] && echo "  docs/                (empty knowledge skeleton)"
[ -e "$OUT/codebases.yaml" ] && echo "  codebases.yaml"
